---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: ansible-role-sshd
      vars:
        - scan: true
  roles:
    - role: stephrobert.openscap
      vars:
        - install_content: true
        - install_oscap: true
        - scan: true